export const WEATHER_ICONS = [
  {},
  {
    Icon: 1,
    isDay: true,
    isNight: false,
    Text: "Sunny",
    src: "https://developer.accuweather.com/sites/default/files/01-s.png",
  },
  {
    Icon: 2,
    isDay: true,
    isNight: false,
    Text: "Mostly Sunny",
    src: "https://developer.accuweather.com/sites/default/files/02-s.png",
  },
  {
    Icon: 3,
    isDay: true,
    isNight: false,
    Text: "Partly Sunny",
    src: "https://developer.accuweather.com/sites/default/files/03-s.png",
  },
  {
    Icon: 4,
    isDay: true,
    isNight: false,
    Text: "Intermittent Clouds",
    src: "https://developer.accuweather.com/sites/default/files/04-s.png",
  },
  {
    Icon: 5,
    isDay: true,
    isNight: false,
    Text: "Hazy Sunshine",
    src: "https://developer.accuweather.com/sites/default/files/05-s.png",
  },
  {
    Icon: 6,
    isDay: true,
    isNight: false,
    Text: "Mostly Cloudy",
    src: "https://developer.accuweather.com/sites/default/files/06-s.png",
  },
  {
    Icon: 7,
    isDay: true,
    isNight: true,
    Text: "Cloudy",
    src: "https://developer.accuweather.com/sites/default/files/07-s.png",
  },
  {
    Icon: 8,
    isDay: true,
    isNight: true,
    Text: "Dreary (Overcast)",
    src: "https://developer.accuweather.com/sites/default/files/08-s.png",
  },
  {
    Icon: 11,
    isDay: true,
    isNight: true,
    Text: "Fog",
    src: "https://developer.accuweather.com/sites/default/files/11-s.png",
  },
  {
    Icon: 12,
    isDay: true,
    isNight: true,
    Text: "Showers",
    src: "https://developer.accuweather.com/sites/default/files/12-s.png",
  },
  {
    Icon: 13,
    isDay: true,
    isNight: false,
    Text: "Mostly Cloudy w/ Showers",
    src: "https://developer.accuweather.com/sites/default/files/13-s.png",
  },
  {
    Icon: 14,
    isDay: true,
    isNight: false,
    Text: "Partly Sunny w/ Showers",
    src: "https://developer.accuweather.com/sites/default/files/14-s.png",
  },
  {
    Icon: 15,
    isDay: true,
    isNight: true,
    Text: "T-Storms",
    src: "https://developer.accuweather.com/sites/default/files/15-s.png",
  },
  {
    Icon: 16,
    isDay: true,
    isNight: false,
    Text: "Mostly Cloudy w/ T-Storms",
    src: "https://developer.accuweather.com/sites/default/files/16-s.png",
  },
  {
    Icon: 17,
    isDay: true,
    isNight: false,
    Text: "Partly Sunny w/ T-Storms",
    src: "https://developer.accuweather.com/sites/default/files/17-s.png",
  },
  {
    Icon: 18,
    isDay: true,
    isNight: true,
    Text: "Rain",
    src: "https://developer.accuweather.com/sites/default/files/18-s.png",
  },
  {
    Icon: 19,
    isDay: true,
    isNight: true,
    Text: "Flurries",
    src: "https://developer.accuweather.com/sites/default/files/19-s.png",
  },
  {
    Icon: 20,
    isDay: true,
    isNight: false,
    Text: "Mostly Cloudy w/ Flurries",
    src: "https://developer.accuweather.com/sites/default/files/20-s.png",
  },
  {
    Icon: 21,
    isDay: true,
    isNight: false,
    Text: "Partly Sunny w/ Flurries",
    src: "https://developer.accuweather.com/sites/default/files/21-s.png",
  },
  {
    Icon: 22,
    isDay: true,
    isNight: true,
    Text: "Snow",
    src: "https://developer.accuweather.com/sites/default/files/22-s.png",
  },
  {
    Icon: 23,
    isDay: true,
    isNight: false,
    Text: "Mostly Cloudy w/ Snow",
    src: "https://developer.accuweather.com/sites/default/files/23-s.png",
  },
  {
    Icon: 24,
    isDay: true,
    isNight: true,
    Text: "Ice",
    src: "https://developer.accuweather.com/sites/default/files/24-s.png",
  },
  {
    Icon: 25,
    isDay: true,
    isNight: true,
    Text: "Sleet",
    src: "https://developer.accuweather.com/sites/default/files/25-s.png",
  },
  {
    Icon: 26,
    isDay: true,
    isNight: true,
    Text: "Freezing Rain",
    src: "https://developer.accuweather.com/sites/default/files/26-s.png",
  },
  {
    Icon: 29,
    isDay: true,
    isNight: true,
    Text: "Rain and Snow",
    src: "https://developer.accuweather.com/sites/default/files/29-s.png",
  },
  {
    Icon: 30,
    isDay: true,
    isNight: true,
    Text: "Hot",
    src: "https://developer.accuweather.com/sites/default/files/30-s.png",
  },
  {
    Icon: 31,
    isDay: true,
    isNight: true,
    Text: "Cold",
    src: "https://developer.accuweather.com/sites/default/files/31-s.png",
  },
  {
    Icon: 32,
    isDay: true,
    isNight: true,
    Text: "Windy",
    src: "https://developer.accuweather.com/sites/default/files/32-s.png",
  },
  {
    Icon: 33,
    isDay: false,
    isNight: true,
    Text: "Clear",
    src: "https://developer.accuweather.com/sites/default/files/33-s.png",
  },
  {
    Icon: 34,
    isDay: false,
    isNight: true,
    Text: "Mostly Clear",
    src: "https://developer.accuweather.com/sites/default/files/34-s.png",
  },
  {
    Icon: 35,
    isDay: false,
    isNight: true,
    Text: "Partly Cloudy",
    src: "https://developer.accuweather.com/sites/default/files/35-s.png",
  },
  {
    Icon: 36,
    isDay: false,
    isNight: true,
    Text: "Intermittent Clouds",
    src: "https://developer.accuweather.com/sites/default/files/36-s.png",
  },
  {
    Icon: 37,
    isDay: false,
    isNight: true,
    Text: "Hazy Moonlight",
    src: "https://developer.accuweather.com/sites/default/files/37-s.png",
  },
  {
    Icon: 38,
    isDay: false,
    isNight: true,
    Text: "Mostly Cloudy",
    src: "https://developer.accuweather.com/sites/default/files/38-s.png",
  },
  {
    Icon: 39,
    isDay: false,
    isNight: true,
    Text: "Partly Cloudy w/ Showers",
    src: "https://developer.accuweather.com/sites/default/files/39-s.png",
  },
  {
    Icon: 40,
    isDay: false,
    isNight: true,
    Text: "Mostly Cloudy w/ Showers",
    src: "https://developer.accuweather.com/sites/default/files/40-s.png",
  },
  {
    Icon: 41,
    isDay: false,
    isNight: true,
    Text: "Partly Cloudy w/ T-Storms",
    src: "https://developer.accuweather.com/sites/default/files/41-s.png",
  },
  {
    Icon: 42,
    isDay: false,
    isNight: true,
    Text: "Mostly Cloudy w/ T-Storms",
    src: "https://developer.accuweather.com/sites/default/files/42-s.png",
  },
  {
    Icon: 43,
    isDay: false,
    isNight: true,
    Text: "Mostly Cloudy w/ Flurries",
    src: "https://developer.accuweather.com/sites/default/files/43-s.png",
  },
  {
    Icon: 44,
    isDay: false,
    isNight: true,
    Text: "Mostly Cloudy w/ Snow",
    src: "https://developer.accuweather.com/sites/default/files/44-s.png",
  },
];
